pipeline {
    agent any

    options {
        skipDefaultCheckout true
        timestamps()
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/AnithaAnnem/my-kafka-task.git'
            }
        }

        stage('Deploy Zookeeper Cluster') {
            steps {
                sh '''
                    echo "Deploying Zookeeper Cluster..."
                    ansible-playbook -i kafkacluster/aws_ec2.yml kafkacluster/site.yml --tags zookeeper
                '''
            }
        }

        stage('Verify Zookeeper Quorum') {
            steps {
                sh '''
                    echo "Verifying Zookeeper quorum..."
                    ansible all -i kafkacluster/aws_ec2.yml -m shell -a "/opt/zookeeper/apache-zookeeper-3.9.2-bin/bin/zkServer.sh status" -u ubuntu
                '''
            }
        }

        stage('Deploy Kafka Brokers') {
            steps {
                sh '''
                    echo "Deploying Kafka Brokers..."
                    ansible-playbook -i kafkacluster/aws_ec2.yml kafkacluster/site.yml --tags kafka
                '''
            }
        }

        stage('Verify Kafka Cluster') {
            steps {
                sh '''
                    echo "Verifying Kafka brokers..."
                    ansible all -i kafkacluster/aws_ec2.yml -m shell -a "/opt/kafka/kafka_2.13-3.7.0/bin/kafka-broker-api-versions.sh --bootstrap-server {{ ansible_host }}:9092" -u ubuntu
                '''
            }
        }

        stage('Create Test Topic') {
            steps {
                sh '''
                    echo "Creating test Kafka topic..."
                    ansible all -i kafkacluster/aws_ec2.yml -m shell -a "/opt/kafka/kafka_2.13-3.7.0/bin/kafka-topics.sh --create --topic test-topic --partitions 3 --replication-factor 3 --bootstrap-server {{ ansible_host }}:9092" -u ubuntu
                '''
            }
        }
    }

    post {
        always {
            echo "Cleaning up workspace..."
            cleanWs()
        }
    }
}
