---

# 0. Include prerequisites
- name: Install prerequisites
  include_tasks: prereqs.yml

# 1. Create zookeeper group
- name: Create zookeeper group
  group:
    name: "{{ zookeeper_group }}"
    state: present
  become: yes

# 2. Create zookeeper user
- name: Create zookeeper user
  user:
    name: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    create_home: no
    shell: /bin/false
  become: yes

# 3. Create directories
- name: Create Zookeeper install and data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: '0755'
  loop:
    - "{{ zookeeper_install_dir }}"
    - "{{ zookeeper_data_dir }}/data"
    - "{{ zookeeper_data_dir }}/log"
    - "{{ zookeeper_install_dir }}/logs"
    - "/var/run/zookeeper"
  become: yes

# 4. Download Zookeeper tarball
- name: Download Zookeeper tarball
  get_url:
    url: "{{ zookeeper_tarball_url }}"
    dest: "{{ zookeeper_install_dir }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
    mode: '0644'
  become: yes

# 5. Extract Zookeeper
- name: Extract Zookeeper
  unarchive:
    src: "{{ zookeeper_install_dir }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
    dest: "{{ zookeeper_install_dir }}/"
    remote_src: yes
    creates: "{{ zookeeper_install_dir }}/apache-zookeeper-{{ zookeeper_version }}-bin"
  become: yes

# 6. Fix ownership recursively
- name: Fix ownership for Zookeeper directories
  file:
    path: "{{ item }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    recurse: yes
  loop:
    - "{{ zookeeper_install_dir }}"
    - "{{ zookeeper_data_dir }}/data"
    - "{{ zookeeper_data_dir }}/log"
    - "{{ zookeeper_install_dir }}/logs"
    - "/var/run/zookeeper"
  become: yes

# 7. Set Zookeeper node ID
- name: Set zookeeper_id
  set_fact:
    zookeeper_id: "{{ play_hosts.index(inventory_hostname) + 1 }}"

# 8. Configure myid via template
- name: Write myid file
  template:
    src: myid.j2
    dest: "{{ zookeeper_data_dir }}/data/myid"
    mode: '0644'
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  become: yes

# 9. Configure zoo.cfg
- name: Configure zoo.cfg
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_install_dir }}/apache-zookeeper-{{ zookeeper_version }}-bin/conf/zoo.cfg"
    mode: '0644'
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  become: yes

# 10. Create systemd service
- name: Create systemd service file for Zookeeper
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    mode: '0644'
  become: yes

# 11. Reload systemd daemon
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes

# 12. Enable and start Zookeeper service
- name: Enable and start Zookeeper service
  systemd:
    name: zookeeper
    enabled: yes
    state: started
  become: yes
