# roles/kafka/vars/main.yml

kafka_version: 3.7.0
kafka_install_dir: /opt/kafka
kafka_data_dir: /tmp/kafka

# Users and groups
kafka_user: kafka
kafka_group: kafka

# Kafka hosts
kafka_hosts:
  - { name: 10.0.11.23, id: 1, ip: "10.0.11.23" }
  - { name: 10.0.11.242, id: 2, ip: "10.0.11.242" }
  - { name: 10.0.11.167, id: 3, ip: "10.0.11.167" }

# Zookeeper hosts
zookeeper_hosts:
  - { name: 10.0.11.120, id: 1, ip: "10.0.11.120" }
  - { name: 10.0.11.68, id: 2, ip: "10.0.11.68" }
  - { name: 10.0.11.179, id: 3, ip: "10.0.11.179" }
